name: 'Build & Test'

on: [push]

jobs:
  build:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet/
      

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: 'Restore dependencies'
      run: dotnet restore

    - name: 'Build solution'
      run: dotnet build --no-restore

    - name: 'Run tests'
      run: dotnet test --no-restore -l 'console;verbosity=normal'

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: dotnet/sdk/JsonRpcX.Tests/coverage/report
        retention-days: 7
