name: 'Publish'

on:
  release:
    types:
      - 'published'

jobs:
  prepare:
    name: 'Prepare'
    runs-on: 'ubuntu-latest'
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: 'Validate tag'
        if: ${{ !startsWith(github.ref_name, 'v') }}
        run: |
          echo "Tag must start with 'v'"
          echo "- Received '${{ github.ref_name }}'"
          exit 1

      - id: version
        name: 'Prepare version'
        env:
          TAG: ${{ github.ref_name }}
        run: |
          echo "version=${TAG:1}" >> "$GITHUB_OUTPUT"

  publish:
    name: 'Publish NuGet'
    runs-on: 'ubuntu-latest'
    needs: prepare
    env:
      NUGET_VERSION: ${{ needs.prepare.outputs.version }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: 'Pack: JsonRpcX'
        working-directory: 'src/JsonRpcX'
        run: |
          echo "NuGet version: $NUGET_VERSION"
          dotnet pack -c Release -p:PackageVersion=$NUGET_VERSION

      - name: 'Push: JsonRpcX'
        working-directory: 'src/JsonRpcX'
        run: |
          dotnet nuget push "bin/Release/JsonRpcX.$NUGET_VERSION.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
