name: 'Publish'

on:
  release:
    types:
      - 'published'

jobs:
  publish:
    name: 'Publish NuGet'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Print release'
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Event release name: ${{ github.event.release.name }}"

      - name: 'Validate version'
        if: ${{ !startsWith(github.event.release.name, 'v') }}
        run: |
          echo "Version must start with 'v'"
          exit 1

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

    # TODO: Actual steps
